from pathlib import Path

project_name = "AI-Product-Manager"

folders = [
    "config",
    "data/raw",
    "data/processed",
    "data/cache",
    "src/core",
    "src/prompts",
    "src/rag",
    "src/agents",
    "src/tools",
    "src/memory",
    "src/checkpointers",
    "src/utils",
    "src/settings",
    "src/databases",
    "src/models/schema",
    "src/api/router",
    "src/api/middleware",
    "src/exceptions",
    "src/monitoring",
    "src/security",
    "src/validators",
    "tests/unit",
    "tests/integration",
    "tests/e2e",
    "logs",
    "scripts",
    "docs",
    ".github/workflows",
]

files = [
    "src/__init__.py",
    "src/core/__init__.py",
    "src/core/llm.py",
    "src/core/client.py",
    "src/core/model_factory.py",
    "src/prompts/__init__.py",
    "src/prompts/templates.py",
    "src/rag/__init__.py",
    "src/rag/embeddings.py",
    "src/rag/retriever.py",
    "src/agents/__init__.py",
    "src/agents/base_agent.py",
    "src/tools/__init__.py",
    "src/tools/registry.py",
    "src/memory/__init__.py",
    "src/memory/vector_store.py",
    "src/checkpointers/__init__.py",
    "src/utils/__init__.py",
    "src/utils/logger.py",
    "src/utils/helpers.py",
    "src/utils/retry.py",
    "src/settings/__init__.py",
    "src/settings/config.py",
    "src/databases/__init__.py",
    "src/databases/connection.py",
    "src/models/__init__.py",
    "src/models/schema/__init__.py",
    "src/models/schema/request.py",
    "src/models/schema/response.py",
    "src/api/__init__.py",
    "src/api/router/__init__.py",
    "src/api/router/health.py",
    "src/api/middleware/__init__.py",
    "src/api/middleware/auth.py",
    "src/api/middleware/rate_limit.py",
    "src/api/middleware/cors.py",
    "src/api/dependencies.py",
    "src/exceptions/__init__.py",
    "src/exceptions/custom_exceptions.py",
    "src/exceptions/handlers.py",
    "src/monitoring/__init__.py",
    "src/monitoring/metrics.py",
    "src/monitoring/tracing.py",
    "src/security/__init__.py",
    "src/security/auth.py",
    "src/security/encryption.py",
    "src/validators/__init__.py",
    "src/validators/input_validator.py",
    "src/main.py",
    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/integration/__init__.py",
    "tests/e2e/__init__.py",
    "tests/conftest.py",
    "scripts/setup.sh",
    "scripts/deploy.sh",
    "scripts/migrate.py",
    "config/logging.yaml",
    "config/prometheus.yml",
    "requirements.txt",
    "requirements-dev.txt",
    "pyproject.toml",
    ".env.example",
    ".gitignore",
    ".dockerignore",
    ".pre-commit-config.yaml",
    "README.md",
    "CONTRIBUTING.md",
    "LICENSE",
    "Dockerfile",
    "docker-compose.yml",
    "Makefile",
    ".github/workflows/ci.yml",
    ".github/workflows/cd.yml",
    "docs/API.md",
    "docs/ARCHITECTURE.md",
]

for folder in folders:
    Path(folder).mkdir(parents=True, exist_ok=True)
    print(f"Created: {folder}")

for file in files:
    Path(file).touch(exist_ok=True)
    print(f"Created: {file}")

print("\nFolder structure created successfully!")
